### ISSUE TITLE
using arduino 189 see errors

### ISSUE THREAD

**Issue by cnc4less** [DominikN/ESP32-http-websocket#2]
just downgraded json to ver 5  ma having errors , any idea ?

ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:956
load:0x40078000,len:0
load:0x40078000,len:13076
entry 0x40078a58
[0;32mI (136) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (136) heap_init: At 3FFAE6E0 len 00011920 (70 KiB): DRAM[0m
[0;32mI (138) heap_init: At 3FFC9BA8 len 00016458 (89 KiB): DRAM[0m
[0;32mI (144) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM[0m
[0;32mI (151) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
[0;32mI (157) heap_init: At 400919DC len 0000E624 (57 KiB): IRAM[0m
assertion "false && "item should have been present in cache"" failed: file "/build/esp-idf/components/nvs_flash/src/nvs_item_hash_list.cpp", line 85, function: void nvs::HashList::erase(size_t)
abort() was called at PC 0x400e0eff on core 0

**Comment by DominikN** [comment]
Hi, just updated the project. Now it is based on platformio, so should work out of the box. To find more details, please read updated README.md file.

**Comment by DominikN** [comment]
platformio.ini contains the right configuration for this project.
